joy/teleop_twist_joy_node:
    ros__parameters:
      axis_linear:
        x: 1
      scale_linear:
        x: 0.7
      scale_linear_turbo:
        x: 1.5
      axis_angular:
        yaw: 2
      scale_angular:
        yaw: 0.4
      enable_button: 4 # L1 shoulder button
      enable_turbo_button: 5 # R1 shoulder button

virtual_joy/teleop_twist_joy_node:
    ros__parameters:
      axis_linear:
        x: 1
      scale_linear:
        x: 0.7
      scale_linear_turbo:
        x: 1.5
      axis_angular:
        yaw: 2
      scale_angular:
        yaw: 0.4
      enable_button: 6 # L1 shoulder button
      enable_turbo_button: 7 # R1 shoulder button

